{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "EOL while scanning string literal (<ipython-input-7-bd72a0f9ffa5>, line 62)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-7-bd72a0f9ffa5>\"\u001b[0;36m, line \u001b[0;32m62\u001b[0m\n\u001b[0;31m    return jsonify({'providers : output})\u001b[0m\n\u001b[0m                                         ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m EOL while scanning string literal\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, jsonify, make_response\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "import uuid\n",
    "from werkzeug.security import generate_password_hash, check_password_hash\n",
    "import jwt\n",
    "import datetime\n",
    "from functools import wraps\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "app.config['SECRET_KEY'] = '123'\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////Downloads/providers.db'\n",
    "\n",
    "db = SQLAlchemy(app)\n",
    "\n",
    "class Providers(db.Model):\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    email = db.Column(db.String(50), unique=True)\n",
    "    name = db.Column(db.String(50))\n",
    "    phonenumber = db.Column(db.Integer)\n",
    "    language = db.Column(db.String(50))\n",
    "    currency = db.Column(db.String(5))\n",
    "    \n",
    "def token_required(f):\n",
    "    @wraps(f)\n",
    "    def decorated(*args, **kwargs):\n",
    "        token = None\n",
    "\n",
    "        if 'access_tok' in request.headers:\n",
    "            token = request.headers['access_tok']\n",
    "\n",
    "        if not token:\n",
    "            return jsonify({'message' : 'Token is missing!'}), 401\n",
    "\n",
    "        try: \n",
    "            data = jwt.decode(token, app.config['SECRET_KEY'])\n",
    "            current = Providers.query.filter_by(id=data['id']).first()\n",
    "        except:\n",
    "            return jsonify({'message' : 'Token is invalid'}), 401\n",
    "\n",
    "        return f(current, *args, **kwargs)\n",
    "\n",
    "    return decorated\n",
    "\n",
    "@app.route('/providers', methods=['GET'])\n",
    "@token_required\n",
    "def get_all_providers(current):\n",
    "\n",
    "    providers = Providers.query.all()\n",
    "\n",
    "    output = []\n",
    "\n",
    "    for providers in providers:\n",
    "        providers_data = {}\n",
    "        providers_data['email'] = providers.email\n",
    "        providers_data['name'] = providers.name\n",
    "        providers_data['phonenumber'] = providers.phonenumber\n",
    "        providers_data['currency'] = providers.currency\n",
    "        providers_data['language'] = providers.language\n",
    "        output.append(providers_data)\n",
    "\n",
    "return jsonify({'providers : output})\n",
    "\n",
    "@app.route('/providers/<email>', methods=['GET'])\n",
    "@token_required\n",
    "def get_one_provider(current, email):\n",
    "\n",
    "    providers = Providers.query.filter_by(email=email).first()\n",
    "\n",
    "    if not providers:\n",
    "        return jsonify({'message' : 'No mail found'})\n",
    "\n",
    "    providers_data = {}\n",
    "    providers_data['email'] = providers.email\n",
    "    providers_data['name'] = providers.name\n",
    "    providers_data['phonenumber'] = providers.phonenumber\n",
    "    providers_data['currency'] = providers.currency\n",
    "    providers_data['language'] = providers.language\n",
    "                    \n",
    "    return jsonify({'providers' : providers_data})\n",
    "\n",
    "@app.route('/providers', methods=['POST'])\n",
    "@token_required\n",
    "def create_providers(current):\n",
    "    \n",
    "    data = request.get_json()\n",
    "    new_provider = Providers(email=str(uuid.uuid4()), name=data['name'], phonenumber=data['phonenumber'], \n",
    "                    currency=data['currency'], language=data['language'])\n",
    "    db.session.add(new_provider)\n",
    "    db.session.commit()\n",
    "\n",
    "    return jsonify({'message' : 'New provider created'})\n",
    "\n",
    "@app.route('/providers/<email>', methods=['PUT'])\n",
    "@token_required\n",
    "def find_providers(current, email):\n",
    "    \n",
    "    providers = Providers.query.filter_by(email=email).first()\n",
    "\n",
    "    if not provider:\n",
    "        return jsonify({'message' : 'No provider found'})\n",
    "\n",
    "    db.session.commit()\n",
    "\n",
    "    return jsonify({'message' : 'The provider has been found'})\n",
    "\n",
    "@app.route('/providers/<email>', methods=['DELETE'])\n",
    "@token_required\n",
    "def delete_provider(current, email):\n",
    "    \n",
    "    providers = Providers.query.filter_by(email=email).first()\n",
    "\n",
    "    if not providers:\n",
    "        return jsonify({'message' : 'No provider found'})\n",
    "\n",
    "    db.session.delete(providers)\n",
    "    db.session.commit()\n",
    "\n",
    "    return jsonify({'message' : 'The provider was deleted'})\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
